#!/bin/sh
#
# As of 0.13, xmonad --recompile will look for a custom build script.

set -e

cd ~/.xmonad

stack install my-xmonad:xmobar --local-bin-path bin/
stack install my-xmonad:xmonad --local-bin-path bin/
ln -sf "$PWD/bin/xmonad" ~/.local/bin/xmonad
ln -sf "$PWD/bin/xmobar" ~/.local/bin/xmobar
