#!/bin/bash

xset dpms 10 0

i3lock -i $(get-wallpaper) -k -n \
     --time-font 'Source Code Pro' --time-color '839496' --time-size 32 \
    --date-font 'Source Code Pro' --date-color '839496' --date-size 16 --date-str "%a %F" \
    --date-pos 'tx:ty+20' \
    --insidever-color '00000000' --insidewrong-color '00000000' --inside-color '00000000' \
    --ringver-color '268bd2' --ringwrong-color 'dc322f' --ring-color '586e75' \
    --verif-color '839496' --keyhl-color '859900' --bshl-color 'dc322f' \
    --verif-text '' --wrong-text '' --noinput-text '' --lock-text '' \
    --layout-font 'Source Code Pro' \
    --keylayout 1 --layout-color 'dc322f' --layout-size 12 \
    --layout-pos 'tx:ty+48' \
    --radius 110 --ring-width 6 \
    --pass-media-keys --pass-screen-keys --pass-volume-keys --pass-power-keys \
    --composite "$@" &

wait $!

xset dpms 0 0
