#!/bin/bash

# maim -u | convert - -blur 11x11 RGB:- | i3lock --raw 1920x1080:rgb --image /dev/stdin
i3lock -i $(get-wallpaper) -k -n \
    --time-font 'Source Code Pro' --timecolor '839496' --timesize 48 \
    --date-font 'Source Code Pro' --datecolor '839496' --datesize 24 --datestr "%a %F" \
    --insidevercolor '00000000' --insidewrongcolor '00000000' --insidecolor '00000000' \
    --ringvercolor '268bd2' --ringwrongcolor 'dc322f' --ringcolor '586e75' \
    --verifcolor '839496' --keyhlcolor '859900' --bshlcolor 'dc322f' \
    --veriftext '' --wrongtext '' --noinputtext '' --locktext '' \
    --keylayout 1 --layoutcolor 'dc322f' --layoutsize 16 \
    --radius 150 --ring-width 12 \
    --pass-media-keys --pass-screen-keys --pass-volume-keys --pass-power-keys \
    --composite "$@"
